### PR TITLE
Add a gitignore and remove untracked files

### PR DESCRIPTION
**Pull request by aaronfranke**
The `.import` folder should not be committed, so it goes in the gitignore.

### CODE REVIEW

**Comment by arypbatista** [comment]
@aaronfranke my only concern here is that demos require a specific import setting so textures repeat. I guess that will require people to manually re-import all images once demos are opened or maybe adding standard import flags to the project configuration. What are your thoughts on this?

**Comment by aaronfranke** [comment]
@arypbatista The import *settings* are stored in `whatever.import` files, the files after importing are stored in the `.import/` folder. This only ignores the latter, and it can be regenerated identically.

**Comment by ChildishGiant** [comment]
https://github.com/github/gitignore/blob/master/Godot.gitignore Here's the reccomended gitignore. Have a look at the discussion on the PR https://github.com/github/gitignore/pull/2546

**Comment by arypbatista** [comment]
Oh, right! Totally forgot. Thanks for the clarification!

**Pull request merged**
