### PR TITLE
Drawing colored, untextured border + Various fixes

### PR DESCRIPTION
**Pull request by Keyaku**
Changes:
- Adds ability to draw a colored, untextured border
- Doesn't hack updates via processing, it now updates the node as necessary
- Unhiding polygon color in-editor
- Refactored code
- Bug fixes

### CODE REVIEW

**Comment by Keyaku** [comment]
Fixes #41.

**Comment by arypbatista** [comment]
@Keyaku Quick question: have you tested the current examples? And, do this deserve a new example?

**Comment by Keyaku** [comment]
AH, no, I didn't. *facepalm* Sorry about that!

I am now and going to work on fixes.

**Comment by arypbatista** [comment]
No problem man! I think it's crucial for new users that wants to use the tool. Docs are not really that important if we have example, so they can be deferred.

**Pull request merged**
